### ISSUE TITLE
URL encode arguments

### ISSUE THREAD

**Issue by cydrobolt** [cydrobolt/pifx#1]
URL encode certain arguments (e.g `label:Hello World`) without encoding the `:` to ensure that spaces and special symbols are passed correctly.
Use `six.moves.urllib.parse.quote_plus(arg)`

**Comment by philosowaffle** [comment]
I don't think this works as intended.  Appears to be encoding `label:Hello World` to `label:Hello+World` which causes the selector to not match any lights. 

Should instead encode to `label:Hello%20World`.  Consider simply doing `arg.replace(" ", "%20")`.
